// examples/preact/custom-devtools/src/CustomDevtoolsPanel.tsx
import { useEffect, useState } from 'preact/hooks'
import { DevtoolsEventClient } from './eventClient.ts'

export default function CustomDevtoolPanel() {
  const [state, setState] = useState<
    { count: number; history: Array<number> } | undefined
  >()

  useEffect(() => {
    // subscribe to the emitted event
    const cleanup = DevtoolsEventClient.on('counter-state', (e) =>
      setState(e.payload),
    )
    return cleanup
  }, [])

  return (
    <div>
      <div>counter state: {state?.count}</div>
      <div>counter history: {JSON.stringify(state?.history)}</div>
    </div>
  )
}

// examples/angular/panel/src/app/devtools/custom-devtools-panel.ts
import { DevtoolsEventClient } from './eventClient';
import { createAngularPanel } from '@tanstack/angular-devtools/utils';

class BasePanel {
  #unsubscribes = [] as Array<() => void>;
  #dispose = () => void 0;

  mount<T extends HTMLElement>(element: T) {
    const plugin = element.ownerDocument.createElement('div');
    element.appendChild(plugin);

    function render(count: number, history: string) {
      plugin.innerHTML = `
       <div>counter state: ${count}</div>
       <div>counter history: ${history}</div>
      `;
    }

    render(0, '');

    this.#unsubscribes.push(
      DevtoolsEventClient.on('counter-state', (e) => {
        const count = e.payload.count ?? 0;
        const history = JSON.stringify(e.payload.history ?? {});
        render(count, history);
      }),
    );

    this.#dispose = () => {
      plugin.remove();
    };
  }

  unmount() {
    this.#unsubscribes.forEach((unsubscribe) => unsubscribe());
    this.#dispose();
  }
}

export const [CustomDevtoolPanel] = createAngularPanel(BasePanel);
