// examples/solid/basic/src/setup.tsx
import { Match, Switch } from 'solid-js'
// query imports
import { useQuery } from '@tanstack/solid-query'

// router imports
import {
  Link,
  Outlet,
  RouterProvider,
  createRootRoute,
  createRoute,
  createRouter,
} from '@tanstack/solid-router'

const rootRoute = createRootRoute({
  component: () => (
    <>
      <div class="p-2 flex gap-2">
        <Link to="/" class="[&.active]:font-bold">
          Home
        </Link>

        <Link to="/about" class="[&.active]:font-bold">
          About
        </Link>
      </div>
      <tsd-json-tree
        value={{ title: 'Test Event', description: 'This is a test event.' }}
      />
      <tsd-button
        text="test"
        value="test"
        variant="secondary"
        onClick={() => console.log('Button clicked!')}
      />
      <hr />
      <Outlet />
    </>
  ),
})

/*
/ demo route
*/
const indexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
  component: function Index() {
    /*
    / demo query resolves after three seconds and returns string
    */
    const exampleQuery = useQuery<string>(() => ({
      queryKey: ['example-query'],
      queryFn: () => {
        return new Promise((resolve) => {
          setTimeout(() => {
            resolve('fetched data')
          }, 3000)
        })
      },
    }))

    return (
      <div class="p-2">
        <h3>Welcome Home!</h3>
        <Switch>
          <Match when={exampleQuery.isLoading}>
            <p>Loading...</p>
          </Match>

          <Match when={exampleQuery.data}>
            <p>{exampleQuery.data}</p>
          </Match>
        </Switch>
      </div>
    )
  },
})

/*
/ demo route
*/
const aboutRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/about',
  component: function About() {
    return (
      <div class="p-2">
        <h3>Hello from About!</h3>
      </div>
    )
  },
})

const routeTree = rootRoute.addChildren([indexRoute, aboutRoute])
export const router = createRouter({ routeTree })

export default function Router() {
  return <RouterProvider router={router} />
}

// examples/react/time-travel/src/setup.tsx
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { ReactQueryDevtoolsPanel } from '@tanstack/react-query-devtools'
import { TanStackRouterDevtoolsPanel } from '@tanstack/react-router-devtools'
import {
  Link,
  Outlet,
  RouterProvider,
  createRootRoute,
  createRoute,
  createRouter,
} from '@tanstack/react-router'
import { TanstackDevtools } from '@tanstack/react-devtools'
import { ZustandTimeTravel } from './zustand-time-travel'

const rootRoute = createRootRoute({
  component: () => (
    <>
      <div className="p-2 flex gap-2">
        <Link to="/" className="[&.active]:font-bold">
          Home
        </Link>{' '}
        <Link to="/about" className="[&.active]:font-bold">
          About
        </Link>
      </div>
      <hr />
      <Outlet />
    </>
  ),
})

const indexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
  component: function Index() {
    return (
      <div className="p-2">
        <h3>Welcome Home!</h3>
      </div>
    )
  },
})
function About() {
  return (
    <div className="p-2">
      <h3>Hello from About!</h3>
    </div>
  )
}

const aboutRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/about',
  component: About,
})

const routeTree = rootRoute.addChildren([indexRoute, aboutRoute])

const router = createRouter({ routeTree })

const queryClient = new QueryClient()

export default function DevtoolsExample() {
  return (
    <>
      <QueryClientProvider client={queryClient}>
        <TanstackDevtools
          plugins={[
            {
              name: 'Tanstack Query',
              render: <ReactQueryDevtoolsPanel />,
            },
            {
              name: 'Tanstack Router',
              render: <TanStackRouterDevtoolsPanel router={router} />,
            },
            {
              name: "Zustand time-travel",
              render: <ZustandTimeTravel />,
            }
          ]}
        />
        <RouterProvider router={router} />
      </QueryClientProvider>
    </>
  )
}
