// examples/preact/custom-devtools/src/App.tsx
import { useState } from 'preact/hooks'

import { createCounter } from './counter'

const counterInstance = createCounter()

export default function App() {
  const [count, setCount] = useState(counterInstance.getCount())

  const increment = () => {
    counterInstance.increment()
    setCount(counterInstance.getCount())
  }

  const decrement = () => {
    counterInstance.decrement()
    setCount(counterInstance.getCount())
  }

  return (
    <div>
      <h1>Custom plugins</h1>
      <h2>Count: {count}</h2>
      <div style={{ display: 'flex', gap: '4px' }}>
        <button onClick={increment}>+ increase</button>
        <button onClick={decrement}>− decrease</button>
      </div>
    </div>
  )
}

// examples/angular/panel/src/app/app.ts
import {
  ChangeDetectionStrategy,
  Component,
  reflectComponentType,
  signal,
  Type,
} from '@angular/core'
import { createCounter } from './counter'
import type { TanStackDevtoolsAngularInit } from '@tanstack/angular-devtools'
import { CustomDevtoolPanel } from './devtools/custom-devtools-panel'
import { TanStackDevtoolsComponent } from '@tanstack/angular-devtools'

@Component({
  selector: 'app-root',
  imports: [TanStackDevtoolsComponent],
  template: `
    <div>
      <h1>Custom plugins</h1>
      <h2>Count: {{ counter.value() }}</h2>
      <div style="display: flex; gap: 4px">
        <button (click)="increment()">+ increase</button>
        <button (click)="decrement()">− decrease</button>
      </div>
    </div>

    <tanstack-devtools [plugins]="plugins()" [eventBusConfig]="{ debug: true }" />
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class App {
  readonly plugins = signal<NonNullable<TanStackDevtoolsAngularInit['plugins']>>([
    {
      name: 'Custom devtools',
      render: CustomDevtoolPanel,
    },
  ])

  readonly counter = createCounter()

  readonly increment = () => this.counter.increment()
  readonly decrement = () => this.counter.decrement()
}
