// examples/preact/custom-devtools/src/App.tsx
import { useState } from 'preact/hooks'

import { createCounter } from './counter'

const counterInstance = createCounter()

export default function App() {
  const [count, setCount] = useState(counterInstance.getCount())

  const increment = () => {
    counterInstance.increment()
    setCount(counterInstance.getCount())
  }

  const decrement = () => {
    counterInstance.decrement()
    setCount(counterInstance.getCount())
  }

  return (
    <div>
      <h1>Custom plugins</h1>
      <h2>Count: {count}</h2>
      <div style={{ display: 'flex', gap: '4px' }}>
        <button onClick={increment}>+ increase</button>
        <button onClick={decrement}>− decrease</button>
      </div>
    </div>
  )
}

// examples/angular/basic/src/app/app.ts
import { ChangeDetectionStrategy, Component, signal } from '@angular/core'
import { createCounter } from './counter'
import type { TanStackDevtoolsAngularInit } from '@tanstack/angular-devtools'
import { TanStackDevtools } from '@tanstack/angular-devtools'
import type { TanStackDevtoolsAngularPlugin } from '@tanstack/angular-devtools';

@Component({
  selector: 'app-root',
  imports: [TanStackDevtools],
  template: `
    <div>
      <h1>Custom plugins</h1>
      <h2>Count: {{ counter.value() }}</h2>
      <div style="display: flex; gap: 4px">
        <button (click)="increment()">+ increase</button>
        <button (click)="decrement()">− decrease</button>
      </div>
    </div>

    @defer (when true) {
      <tanstack-devtools [plugins]="plugins()" [eventBusConfig]="{ debug: true }" />
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class App {
  readonly plugins = signal<TanStackDevtoolsAngularPlugin[]>([
    {
      name: 'Custom devtools',
      render: () => import('./devtools/custom-devtools-panel'),
    },
  ])

  readonly counter = createCounter()

  readonly increment = () => this.counter.increment()
  readonly decrement = () => this.counter.decrement()
}
